#pragma once

typedef unsigned int ERROR;

#define ERROR_OK 0
#define ERROR_CANNOT_OPEN_FILE 1
#define ERROR_CANNOT_CREATE_FILE 2
#define ERROR_FILE_ALREADY_EXISTS 3

#define ERROR_SHA256_INIT_FAIL 4
#define ERROR_SHA256_DIGEST_ERROR 5
#define ERROR_SHA256_CALC_FAIL 6

#define ERROR_PARAMS 50
#define ERROR_DELETE_FILE_FAIL 51
#define ERROR_FILE_NOT_OPEN 52
#define ERROR_FILE_READ_FAIL 53
#define ERROR_NO_DATA 54

#define ERROR_AES_CTX_INIT 60
#define ERROR_AES_ENCRYPT_INIT 61
#define ERROR_AES_ENCRYPT_UPDATE 62
#define ERROR_AES_ENCRYPT_FINAL 63
#define ERROR_AES_ENCRYPT_FAIL 64
